<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="2" time="16.890" timestamp="2021-05-08T18:16:09.914330" hostname="PC-20210425PVWR"><testcase classname="test_dir.test_publish.TestPublish" name="test_login_case" time="14.457" /><testcase classname="test_dir.test_publish.TestPublish" name="test_publish" time="2.094"><failure message="AttributeError: 'TestPublish' object has no attribute 'page'">self = &lt;test_dir.test_publish.TestPublish object at 0x000001F80A82FFA0&gt;
browser = &lt;selenium.webdriver.chrome.webdriver.WebDriver (session="2c5fedeb1e72a6a50ac478ad84a1dd6e")&gt;
base_url = 'http://localhost/phpwind/'

    @pytest.mark.run(order=2)
    def test_publish(self, browser, base_url):
&gt;       page = self.page
E       AttributeError: 'TestPublish' object has no attribute 'page'

test_dir\test_publish.py:25: AttributeError</failure></testcase></testsuite></testsuites>